### ISSUE TITLE
geen push-rechten

### ISSUE THREAD

**Issue by jstolp** [ermst4r/channel-creator#1]
omdat ie leeg is?

`{"country":[{"id":1,"country_name":"Nederland"},{"id":2,"country_name":"Belgie"},{"id":3,"country_name":"Duitsland"}],"channel":[{"id":1,"channel_name":"first channel","channel_image":"https:\/\/stolpsys.nl\/img\/ceo_small.jpg","country_id":1,"channel_types":[{"id":1,"type":"Fashion","channel_id":"1"},{"id":2,"type":"Normal","channel_id":"1"}],"channel_mapping":[{"id":1,"field_name":"category","description":"category_path","field_type":1,"type_id":1},{"id":2,"field_name":"category_path","description":"category_path","field_type":1,"type_id":1},{"id":3,"field_name":"color","description":"color","field_type":2,"type_id":1},{"id":4,"field_name":"color_brite","description":"color_brite","field_type":2,"type_id":2}]},{"id":2,"channel_name":"2nd channel (erm_test)","channel_image":"http:\/\/example.com\/","country_id":2,"channel_types":[{"id":3,"type":"2nd chan first type","channel_id":"2"}],"channel_mapping":[{"id":5,"field_name":"ean","description":"ean","field_type":2,"type_id":1}]}]}`

dit is de response en de tests:

Finished in 0.101 seconds
2 tests, 10 assertions, 0 failures, 0 skipped

**Comment by ermst4r** [comment]
lekker bezig, ga straks ff checken
